# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb5db5e95e75c87126505270bbf4d54908f30a0f1d0b528c978eac339980f877f937656393998420e6c960e21859de455839ad66db4c70ac0c56a63fd9846ff6
  paypal_host: https://www.sandbox.paypal.com
  app_host: http://58515ca9.ngrok.io
test:
  secret_key_base: 1629f1d3db092b658c87a8c1ed4342be79cb94830de2367b32b29e95553294af27570716c5e76c0b4e5ffb831c612b0bb405b2a82f3bbc8942ccc36cca959255

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  app_host: https://launchschool.com/
